### ISSUE TITLE
Dockerfile won't build as implemented

### ISSUE THREAD

**Issue by hhefzi** [MannLabs/CKG#17]
RUN wget -P /CKG https://data.mendeley.com/datasets/mrcf7f4tc2/1/files/c0d058a2-adfa-4b96-97d9-c9ec7fc5adb9/data.tar.gz?dl=1
RUN tar -xzf data.tar.gz

fails because the file will be created at /CKG/data.tar.gz?dl=1

changing to:
RUN wget -O /CKG/data.tar.gz
RUN tar -xzf /CKG/data.tar.gz

will let the build complete without errors but I'm not sure how it interacts with the following lines
ADD . /CKG
ENV PYTHONPATH "${PYTHONPATH}:/CKG/src"

**Comment by albsantosdel** [comment]
Great! The wget needs to change to the --output option. 
I am not sure what you mean with how it will interact. The data directory is not part of CKG's codebase and only contains data. The directory structure is then:
CKG/ 
|── data/
│        |── curated/
│        |── databases/
│        |── downloads/
│        |── experiments/
│        |── imports/
│        |── ontologies/
│        |── reports/
│        |── users/
|── src/

**Comment by hhefzi** [comment]
Just wasn't sure if changing to

RUN wget -O /CKG/data.tar.gz
RUN tar -xzf /CKG/data.tar.gz

was enough or if the following lines needed to be changed as well (and if so, to what).

**Comment by albsantosdel** [comment]
I modified these lines. Thanks!
