### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by im281** [MannLabs/CKG#19]
**Describe the bug**
Docker build fails
Step 14/54 : ADD /resources/jre-8u221-linux-x64.tar.gz /usr/local/oracle-jre8-installer-local
ADD failed: stat /var/lib/docker/tmp/docker-builder253828483/resources/jre-8u221-linux-x64.tar.gz: no such file or directory

**To Reproduce**
run docker build -t mycontainer .

**Comment by albsantosdel** [comment]
A requirement to run the Docker is Java SE Runtime Environment. Please go to https://www.oracle.com/java/technologies/javase-jre8-downloads.html and download the jre-8u221-linux-x64.tar.gz file. Once downloaded, place it in CKG/resources/. (https://ckg.readthedocs.io/en/latest/intro/getting-started-with-docker.html)

**Comment by im281** [comment]
ahh thank you!
