### ISSUE TITLE
Docker image build errors

### ISSUE THREAD

**Issue by im281** [MannLabs/CKG#20]
I had a build error earlier and the solution was this:

A requirement to run the Docker is Java SE Runtime Environment. Please go to https://www.oracle.com/java/technologies/javase-jre8-downloads.html and download the jre-8u221-linux-x64.tar.gz file. Once downloaded, place it in CKG/resources/. (https://ckg.readthedocs.io/en/latest/intro/getting-started-with-docker.html)

However, the latest jre is 251 so I updated the docker file and now I get this error:

![image](https://user-images.githubusercontent.com/10081392/82915099-2c0edf80-9f25-11ea-9067-650e5e148c8c.png)

**Comment by albsantosdel** [comment]
We have tested the docker with the java version specified in the dockerfile. If you need/want to use a different version make sure you change the paths to the new file everywhere. I maked in the image where I believe it could be giving the error.
![error](https://user-images.githubusercontent.com/1425851/82917127-496a9a80-9f73-11ea-9630-793812255a87.png)

**Comment by im281** [comment]
cool ty!
