### ISSUE TITLE
Switch to OpenJDK instead of proprietary Oracle JDK

### ISSUE THREAD

**Issue by vemonet** [MannLabs/CKG#23]
**Is your feature request related to a problem? Please describe.**
Anyone wanting to start the CKG needs to go to Oracle and download their proprietary Java installation which is proprietary **not properly versioned** (e.g. I cannot install exactly the same version as you)

**Describe the solution you'd like**
Remove Oracle JDK dependency and use OpenJDK
If possible I would like the CKG to use OpenJDK.

This will allow you to properly build and push the Docker Image so anyone who wants to run the CKG will be able to do it in one click instead of fiddling with Oracle JDK download, and the Dockerfile

**Describe alternatives you've considered**

**Additional context**
It will be much more easier for us to contribute, and redistribute this awesome project!

**Comment by albsantosdel** [comment]
Excellent suggestion! I'll make the necessary changes and test it.

**Comment by vemonet** [comment]
Nice, thanks! 

If you switch to OpenJDK you will not face any licensing issue anymore for redistribution, and will be able to push the current Docker image to DockerHub (so that people can just `docker run` this development instance to test it easily, and avoid new issue appearing in the docker build)

**Comment by albsantosdel** [comment]
Hi, 

I just pushed some changes to the **_develop_** branch that should solved the issues you had before and this version also uses OpenJDK.
I am working on this: https://github.com/MannLabs/CKG/pull/25#issuecomment-651542649
But if you want you can check it out.

Thank you again for the excellent recommendations.

**Comment by vemonet** [comment]
Thanks a lot! I tried it and it seems to work perfectly! (even if the image is a bit big)

I loaded the image to DockerHub to make it easier to redeploy it: https://hub.docker.com/repository/docker/umids/ckg 

About 20G size
