### ISSUE TITLE
Database install question

### ISSUE THREAD

**Issue by nickhsmith** [MannLabs/CKG#27]
Hello, when I was installing CKG according to the documentation provided here: https://ckg.readthedocs.io/en/latest/intro/getting-started-with-build.html

One of the images shows the structure of the CKG directory as having many different databases

![image](https://user-images.githubusercontent.com/7143411/87303647-cb0e8b80-c513-11ea-91c1-8385e1cf99e1.png)

After running the command:
However after following the instructions and running `python builder.py -b full -u neo4j 2> test.log ` it seems like a majority of the databases are not installed. Looking in my CKG directory I see only the following:

`ls CKG/data/databases/ `

```DrugBank/     
   Jensenlab/    
   PhosphoSitePlus/ 
   STITCH/    
   STRING/      
   UniProt/    
   disgenet/  
```

Another thing I notice is that despite running this overnight, it exited in like 20 minutes. Attached is the log file mentioned above from builder.py
[test.log](https://github.com/MannLabs/CKG/files/4913337/test.log)

Thank you, and I appreciate your response. Another question I have is will the documentation for the Advanced Features be updated here?
https://ckg.readthedocs.io/en/latest/advanced_features/import-statistics.html

**Comment by albsantosdel** [comment]
The '_full_' build option creates a directory in the database folder for each database downloaded, however, most of these directories will be removed once the import files are generated. This is to avoid using too much disk space and only databases that are needed for mapping are kept (UniProt, STRING,...). 

In the log file you attached I can see several errors: 
1) DrugBank database was not found (**see** https://ckg.readthedocs.io/en/latest/intro/getting-started-with-build.html#build-neo4j-graph-database) 
2) DisGeNET parsing failed. The file format from this database may have changed so I will modify the parser.
3) You ran out of disk space at some point and then the import process failed.

**3.** was the main issue. Even though the builder removes most of the downloaded databases, it still requires quite a bit of disk space both for downloaded databases and for the generated import files (imports/). If possible, free some disk space before building CKG's graph database, alternatively, you can use the dump installation (**see** https://ckg.readthedocs.io/en/latest/intro/getting-started-with-build.html#from-the-provided-dump-file), which requires less (temporary) disk space.

I will keep the issue open until (**2.**) is solved.

Regarding your question about documentation, updates on documentation are coming up soon.

Thank you for opening the issue.

**Comment by albsantosdel** [comment]
Solved issue with DisGeNET database [(here)](https://github.com/MannLabs/CKG/commit/8e6b760a5df3a2d74439d551fc42f14aa40d4c84#diff-b3e20a37d2b0f5db99701dd8774bc5fb)
