### ISSUE TITLE
Data Upload to Project

### ISSUE THREAD

**Issue by nickhsmith** [MannLabs/CKG#29]
I have managed to create a project using the CKG interface, but am having a problem with the data upload step for a project with the ID = P0000007. I encounter this error on the CKG local interface:  
`Error: No data was uploaded for project: P0000007. Review your experimental design and data files.`

I am trying to upload the following files (the txt files are the outputs from MaxQuant):
ExperimentalDesign_P0000007.xlsx, ClinicalData_P0000007.xlsx, protein_groups.txt, peptides.txt, and OxidationSites.txt

I am unsure if my formatting in the xlsx files is correct

ExperimentalDesign  
![image](https://user-images.githubusercontent.com/7143411/88285349-35cb7e00-ccef-11ea-8c41-844670f4ccb5.png)

ClinicalData  
![image](https://user-images.githubusercontent.com/7143411/88285469-6ca19400-ccef-11ea-95b2-601707af86f6.png)

And my MaxQuant file has headers of the following form, where 1_M1 is the first technical replicate for the sample M1. So in this file there would be 2 samples each with 3 replicates for a total of 6 measurements:
Intensity 1_M1
Intensity 2_M1
Intensity 3_M1
Intensity 1_M2
Intensity 2_M2
Intensity 3_M2

My question is how should the Experimental and Clinical spreadsheets be set up? Should each replicate be given its own line? .

To futher illustrate this point. In this table, also provided in the documentation, I don't understand how the 2nd and 3rd rows are generated as the KO2 becomes KO (same with KO3 -> KO). And how should an experiment with these 5 MaxQuant measurement headers be represented by the ExperimentalDesign and ClinicalDesign spreadsheets.

Technical replicate | Analytical sample id | Timepoint | Result
-- | -- | -- | --
1 | KO_plate1 |   | 1_KO_plate1
1 | KO2_plate1 | 0 | 1_KO_plate1_0
1 | KO3_plate1 | 30 | 1_KO_plate1_30
1 | KO4_plate2 |   | 1_KO4_plate2
2 | KO4_plate2 |   | 2_KO4_plate2

Thank you in advance.

**Comment by albsantosdel** [comment]
In CKG, **technical replicates** are measurements performed on the same analytical sample and they are aggregated when parsing the proteomics file (median aggregation). In that case, the experimental design would look like this:

subject   external_id | biological_sample external_id | analytical_sample external_id
-- | -- | --
M1 | M1 | M1
M2 | M2 | M2

In this case, we have 2 subjects from which we obtained 1 biological sample that we split into 1 analytical sample from each and we run 3 technical replicates from each analytical sample.

If instead you have biologically different samples (i.e timepoints) those should then be considered different biological samples. The experimental design should be for instance:

subject   external_id | biological_sample external_id | analytical_sample external_id
-- | -- | --
M1 | 1 | 1_M1
M1 | 2 | 2_M1
M1 | 3 | 3_M1
M2 | 1 | 1_M2
M2 | 2 | 2_M2
M2 | 3 | 3_M2

In this case, we have 2 subjects from which we obtained 1 biological sample at each timepoint (3 timepoints) that we split into 1 analytical sample from each.

If I understand correctly, your experiment is more like the second case. If that is correct, the experimental design proposed would already work with your proteomics file. 

To create the clinical dataset, please, follow the instructions [(here)](https://ckg.readthedocs.io/en/latest/getting_started/upload-data.html#clinical-data).

**Comment by nickhsmith** [comment]
My experiment is actually like the first one, in reality, I have 10 samples each with 3 technical replicates. Attached are my files, and I'm still getting the same error 

`Error: No data was uploaded for project: P0000007. Review your experimental design and data files.`

I've uploaded only the first 10 lines of the relevant proteomics files. I still can not add this data to a project

[ClinicalData__P0000007.xlsx](https://github.com/MannLabs/CKG/files/4982393/ClinicalData__P0000007.xlsx)
[ExperimentalDesign__P0000007.xlsx](https://github.com/MannLabs/CKG/files/4982394/ExperimentalDesign__P0000007.xlsx)
[Oxidation_sites_modified_head.txt](https://github.com/MannLabs/CKG/files/4982395/Oxidation_sites_modified_head.txt)
[peptides_modified_head.txt](https://github.com/MannLabs/CKG/files/4982397/peptides_modified_head.txt)
[proteinGroups_modified_head.txt](https://github.com/MannLabs/CKG/files/4982398/proteinGroups_modified_head.txt)

**Comment by albsantosdel** [comment]
Can you remove the folder 'CKG/data/experiments/P0000007/proteomics' and try again? I think there is a conflict with previously created files.

The experimental design and clinical data work for me:
![image](https://user-images.githubusercontent.com/1425851/88554817-3e8dbe00-d027-11ea-9e5b-0726489565db.png)

The proteomics data contains only contaminants so it cannot create any links in the database but the file is correctly converted into CKG identifiers.

LFQ intensity   1_AS1616 | LFQ intensity 2_AS1616 | LFQ intensity 3_AS1616 | LFQ intensity 1_AS1617
-- | -- | -- | --
0 | 0 | 0 | 0
72122000 | 213280000 | 266280000 | 454860000
8387700 | 16773000 | 0 | 10513000
52580000 | 43520000 | 45168000 | 51372000
71911000 | 118490000 | 139460000 | 55448000
18651000 | 17047000 | 26208000 | 36054000

**Comment by nickhsmith** [comment]
I have since removed P0000007 from the data/experiments directory and have retried on many occasions with the same error. When I try it with the shortened (head) data I get something new though:
`Error 'Series' object has no attribute 'stack'. Importing experiment P0000012. Data type proteomics.`

Does this error correspond to the fact that these lines are the contaminants?

**Comment by albsantosdel** [comment]
In order to reproduce the issue, Could you provide some example files with proteins that are not contaminants? 

The second error is indeed because there are no proteins left to import once contaminants are removed. I will improve the error message.

**Comment by nickhsmith** [comment]
I am starting from scratch, and hopefully telling the whole tale.

## Project Creation  
I originally create a new project 
![Screenshot from 2020-07-29 10-19-48](https://user-images.githubusercontent.com/7143411/88777520-993e2b80-d187-11ea-8a93-2bb603977159.png)
![Screenshot from 2020-07-29 10-20-44](https://user-images.githubusercontent.com/7143411/88777516-98a59500-d187-11ea-87d3-9af9920d46b7.png)

which generates a new project ID: **P0000014** and gives me the prompt to download the Experimental and Clinical design templates which I do. I populate them as we discussed before.
[ClinicalData__P0000014.xlsx](https://github.com/MannLabs/CKG/files/4993708/ClinicalData__P0000014.xlsx)
[ExperimentalDesign_P0000014.xlsx](https://github.com/MannLabs/CKG/files/4993711/ExperimentalDesign_P0000014.xlsx)

## Data Upload  
From there I go to the data upload option, and select P0000014

I upload the experimental file
![Screenshot from 2020-07-29 10-33-01](https://user-images.githubusercontent.com/7143411/88778041-4618a880-d188-11ea-9e99-b24167cc8139.png)

I upload the clinical file
![Screenshot from 2020-07-29 10-33-17](https://user-images.githubusercontent.com/7143411/88778061-4f097a00-d188-11ea-97ef-992159c7da48.png)

I then upload the 3 proteomics files by selecting proteomics, MaxQuant and then in order
1. Protein Groups 
2. Peptides
3. Phospho STY sites

selecting from the file browser 
1.  [proteinGroups_10individuals_modified.txt](https://github.com/MannLabs/CKG/files/4993719/proteinGroups_10individuals_modified.txt)
2. [peptides_modified.txt](https://github.com/MannLabs/CKG/files/4993720/peptides_modified.txt)
3. [Oxidation (M)Sites_modified.txt](https://github.com/MannLabs/CKG/files/4993721/Oxidation.M.Sites_modified.txt)

Before finally clicking the blue "Upload to CKG" button.
After ~10 seconds I am directed to this message
`Error: No data was uploaded for the project: P0000014. Review your experimental design and data files.`
![Screenshot from 2020-07-29 10-34-53](https://user-images.githubusercontent.com/7143411/88778405-c5a67780-d188-11ea-8f85-a2a55b2e56d8.png)


My proteomics files are saved in the MS-DOS style of text file. So each line is ended using the `\r\n` character code. And only differs from what MQ provides by reordering the style of the technical replicates to match `replicateNumber_analyticalSampleID`

I have tried this also using the UNIX style of text file, where each line is ended using the `\n` character code. Both with the same result.


Thank you for your time, and help! I really appreciate it.

**Comment by albsantosdel** [comment]
Thank you for the very well described issue and the details.
 
I have tried again to upload the data with the files you posted and I can see that the mapping to CKG identifiers is done correctly, and the proteomics parser also works. You can see the generated files in: **CKG/data/imports/experiments/**_**(Project_id)**_. 
However, the protein identifiers in your proteinGroups file are not found in the database and that is why no data (proteomics) are uploaded into CKG's graph database. Even though the protein _P02649_ is in the database, the identifiers in your file have additional labels to distinguish between isoforms: _E3, _E4.

It is a very specific case, the solution I can think of right now is to create these nodes in the database and copy all the existing relationships of node _P02649_ and then upload the data again.

You can create the new nodes and copy the relationships using these queries:

```cypher
MATCH (n:Protein{id:'P02649'}) 
// create copies of the node
CREATE (n3:Protein) 
SET n3.accession=n.accession, n3.synonyms=n.synonyms, n3.taxid=n.taxid, n3.name="APOE_3",n3.id="P02649_E3"
CREATE (n4:Protein) 
SET n4.accession=n.accession, n4.synonyms=n.synonyms, n4.taxid=n.taxid, n4.name="APOE_4",n4.id="P02649_E4"

//create a copy of the relationships for P02649_E3
MATCH (n:Protein{id:"P02649"})-[r]->(e)
WITH r, e
MATCH (n:Protein{id:"P02649_E3"})
WITH r, e, n
CALL apoc.create.relationship(n, type(r), {}, e) YIELD rel
RETURN rel

//create a copy of the relationships for P02649_E4
MATCH (n:Protein{id:"P02649"})-[r]->(e)
WITH r, e
MATCH (n:Protein{id:"P02649_E4"})
WITH r, e, n
CALL apoc.create.relationship(n, type(r), {}, e) YIELD rel
RETURN rel
```

**Comment by nickhsmith** [comment]
Thank you for your help!
