### ISSUE TITLE
Dealing with multiple diseases

### ISSUE THREAD

**Issue by nickhsmith** [MannLabs/CKG#33]
I had a question about designating different diseases for a particular patient in the ClinicalData.xlsx file.

In the project creation process, I can select multiple disease in our case diseases that are often linked or similar (like inflammatory bowel disease, and Chron's disease)

However, I am unsure how to input the disease for these patients in the ClinicalData.xlsx file. Should I only choose one disease? Can I designate both of them using a separate delimiter? 
![image](https://user-images.githubusercontent.com/7143411/89415074-a92bb180-d72b-11ea-929a-ff22ec40d15d.png)
![image](https://user-images.githubusercontent.com/7143411/89415306-f9a30f00-d72b-11ea-96c0-cfa1c5e54041.png)

**Comment by albsantosdel** [comment]
You can use the same delimiter _"|"_ to list all the diseases.

**Comment by nickhsmith** [comment]
So is the way I have it written above, the correct way? I don't see any clinical information being transmitted to the graph

![image](https://user-images.githubusercontent.com/7143411/90157906-9ac64100-dd8e-11ea-8f07-0ec7e1226f26.png)

**Comment by albsantosdel** [comment]
The clinical tab will show clinical variables (SNOMED-CT) that you have uploaded. The diseases studied are not variables but just information associated to your project so that information will show in the Project Information tab.

**Comment by albsantosdel** [comment]
I am closing this pull request _for now_ because of inactivity and outdated code.
@nickhsmith  we can always reopen it though! :)
