### ISSUE TITLE
Improve documentation of data dump

### ISSUE THREAD

**Issue by cthoyt** [MannLabs/CKG#42]
**Is your feature request related to a problem? Please describe.**

We're working on integrating CKG as a benchmarking data set in [PyKEEN](https://github.com/pykeen/pykeen) in this PR (https://github.com/pykeen/pykeen/pull/213). We were able to automate download of version 2 of the data from the Mendeley/Elsevier [page](https://data.mendeley.com/datasets/mrcf7f4tc2/2).

However, after decompression, we were not able to understand the contents of the `downloads/`  or `reports/` folders. It appears the `downloads/` folder contains zip archives with images. However, the structure and nomenclature within `reports/` is not intuitive. 

I guessed that the h5 files could be opened with Pandas, but I got some errors about the data formatting, so that might not be correct. Further, each folder has the same structure of files, but without context as to what P0000001-P0000006 mean.

From the `imports/` folder, we were able to extract 7,617,419 entity types, 11 relation types, and 26,691,525 triples. This is quite far from what's claimed in the CKG paper, so I assume some of the data is in the `reports/` folder.

**Describe the solution you'd like**

Please add a README to each directory in the data dump that describes the structure of the data, the file types, and schemata for the data contained within. Code examples of how to load the data would be appreciated as well.

Thanks for providing this resource - we hope that inclusion in PyKEEN will enable more people to work with your dataset and would love to explain further if you're interested. Feel free to reach out with an issue on PyKEEN's repo, by twitter https://twitter.com/cthoyt, or by email cthoyt@gmail.com

**Comment by albsantosdel** [comment]
Dear @cthoyt,

Thank you very much for your interest and your useful comment! It would be great to integrate CKG with PyKEEN and I would definitely like to hear more about it. I will contact you by email soon.

It is a really good idea to include a README and I will work on it in the next days to make the structure clearer and also more intuitive. I am also including here a diagram of each of the directories in CKG/ to also help clarify.
![CKG_directories](https://user-images.githubusercontent.com/1425851/102056454-b1d47880-3dec-11eb-9e37-e4c5290cbbba.jpeg)


The files in the report folder are indeed h5 format and there is an example of how to access the contents in this [notebook](https://github.com/MannLabs/CKG/blob/master/src/notebooks/recipes/Access%20Project%20Report.ipynb). Also, you can find in the report module how the content is parsed ([here](https://github.com/MannLabs/CKG/blob/74babdb2dcd6c0cc57a41a9d25b866a324c18e68/src/report_manager/report.py#L105)).

The entities and relationships included in the imports/ folder are only the ones related to the licensed databases (DrugBank, PhosphoSitePlus) and the SNOMED-CT terminology. The dump file together with these databases and terminology and the missing relationships should then sum to the numbers specified in the Biorxiv version of the manuscript.

I'll be happy to help if you still have troubles getting the numbers. Please, let me know any other documentation that may help you and others. 

Thank you very much again.
