### ISSUE TITLE
Make code pip-installable

### ISSUE THREAD

**Issue by cthoyt** [MannLabs/CKG#43]
A lot of the documentation is about how to configure the code to be run. Making the code installable with pip would greatly decrease complexity and make python users directly able to use your code.

Would you be willing to accept a PR for this? It would involve changing the repository to the typical `src/` layout, in which there's a folder `src/ckg/` where all of the python code goes. Then, a `setup.cfg` file and `setup.py` file could be added so you could do the following:

```
git clone https://github.com/MannLabs/CKG.git
cd CKG
pip install .
```

This would also put the `requirements.txt` information into `setup.cfg`. Ultimately it would simplify https://ckg.readthedocs.io/en/latest/intro/getting-started-with-build.html as well since some of this could be done with python module execution

**Comment by albsantosdel** [comment]
Dear @cthoyt,

Thank you also for this proposal. It does make total sense to make CKG pip installable. It is in the toDo list and it would of course be great if you could contribute! A PR would be very much appreciated!

**Comment by albsantosdel** [comment]
CKG python libraries can now be installed by running:
``` python
python setup.py install
```

You can follow the instructions [here](https://ckg.readthedocs.io/en/latest/intro/getting-started-with-requirements.html)
