### ISSUE TITLE
Add system requirements more prominently

### ISSUE THREAD

**Issue by enryH** [MannLabs/CKG#44]
**Is your feature request related to a problem? Please describe.**
I needed some time to find the information on how much disk space I actually need to get a running installation of the CKG. 

**Describe the solution you'd like**
Could be added to the main page under _Cloning and installing_.

> Installation requires >= 80 GB of disk space. See details [here ](https://github.com/MannLabs/CKG/blob/master/docs/source/system_requirements.rst)

**Additional context**
I can create a pull-request, if you like.

**Comment by albsantosdel** [comment]
Good point @enryH! You can submit it as PR! Thank you!
