### ISSUE TITLE
docker : Permission denied for mkdr

### ISSUE THREAD

**Issue by prabinrs** [MannLabs/CKG#46]
Docker in windows got the following error 
ERROR [31/78] RUN service neo4j start &&     sleep 30 &&     service neo4j stop &&     cat /var/log/neo4j/neo  0.3s
------
 > [31/78] RUN service neo4j start &&     sleep 30 &&     service neo4j stop &&     cat /var/log/neo4j/neo4j.log:
#36 0.267 Active database: graph.db
#36 0.268 Directories in use:
#36 0.268   home:         /var/lib/neo4j
#36 0.268   config:       /etc/neo4j
#36 0.268   logs:         /var/log/neo4j
#36 0.268   plugins:      /var/lib/neo4j/plugins
#36 0.268   import:       NOT SET
#36 0.268   data:         /var/lib/neo4j/data
#36 0.268   certificates: /var/lib/neo4j/certificates
#36 0.268   run:          /var/run/neo4j
#36 0.270 mkdir: cannot create directory ‘/var/run/neo4j\r’: Permission denied
------
executor failed running [/bin/sh -c service neo4j start &&     sleep 30 &&     service neo4j stop &&     cat /var/log/neo4j/neo4j.log]: exit code: 1

**Comment by RoseM001** [comment]
I have the exact same error on Windows 10.

 => ERROR [30/77] RUN service neo4j start &&     sleep 30 &&     service neo4  0.7s
------
 > [30/77] RUN service neo4j start &&     sleep 30 &&     service neo4j stop &&     cat /var/log/neo4j/neo4j.log:
#34 0.641 Active database: graph.db
#34 0.643 Directories in use:
#34 0.643   home:         /var/lib/neo4j
#34 0.643   config:       /etc/neo4j
#34 0.643   logs:         /var/log/neo4j
#34 0.643   plugins:      /var/lib/neo4j/plugins
#34 0.643   import:       NOT SET
#34 0.643   data:         /var/lib/neo4j/data
#34 0.643   certificates: /var/lib/neo4j/certificates
#34 0.643   run:          /var/run/neo4j
#34 0.647 mkdir: cannot create directory ‘/var/run/neo4j\r’: Permission denied
------
executor failed running [/bin/sh -c service neo4j start &&     sleep 30 &&     service neo4j stop &&     cat /var/log/neo4j/neo4j.log]: exit code: 1

**Comment by albsantosdel** [comment]
Hi @prabinrs and @RoseM001 

My apologies for this error. I was not able to reproduce it with the Docker version and OS I had but we are now trying to solve it. We'll keep you posted.

Thank you.

**Comment by albsantosdel** [comment]
Hi, 

The issues should now be solved. The error was quite obscure and only affected Windows. Windows added '\r' characters in the Neo4j config file and this affected the creation of directories when running Neo4j. Knowing it now, it is somehow clear when you look at the error but unfortunately it was not so obvious and took many rounds to find out.

Apologies for the delay in solving this issue, and please let us know if you find any other hiccups when building the container.
Again, thank you for your help!
