### ISSUE TITLE
Latest neo4j dump referenced in dockerfile unavailable

### ISSUE THREAD

**Issue by OmicMD** [MannLabs/CKG#59]
Love the concept, project, and tech. I'm trying to build this but the ckg_190521_neo4j_4.2.3.dump file referenced in the dockerfile is unavailable from the Mendeley site.

Using the latest available dump file, ckg_201020_neo4j_3.5.20.dump, forces a neo4j downgrade to 3.5 and results in other issues when trying to load neo4j and jupyter plugins, commercial databases, and the ckg app.

Some guidance would be great, I'm excited about this project!

**Comment by albsantosdel** [comment]
Thank you for your comment! 
The dump file became too large for Mendeley data so we are trying to serve it locally instead. I will change the URL asap. I will also post here the link.

Thank you again.

**Comment by OmicMD** [comment]
Thanks for the quick response Alberto!

**Comment by albsantosdel** [comment]
I am closing this issue for because of inactivity and outdated code.
