### ISSUE TITLE
[docker build] No Durg node information of Neo4j database

### ISSUE THREAD

**Issue by ghost** [MannLabs/CKG#67]
Hello， I build CKG via Docker container, but there are no node and relation for Durg in Neo4j database, I have been put the Drugbank data file in data folder,

![image](https://user-images.githubusercontent.com/69947683/142710139-5ed3369d-13c4-47dc-b397-64e703b6b35b.png)

**Comment by albsantosdel** [comment]
Hi, 
Once the database is running you need to use the ```Minimal update``` to include the licensed databases:
[Minimal update](https://ckg.readthedocs.io/en/latest/ckg_builder/graphdb-builder.html#minimal-update)
Make sure that you have the correct files in the DrugBank folder:
![image](https://user-images.githubusercontent.com/1425851/154010719-abda0c97-4761-4924-8e7e-45e9e88cb54e.png)

The minimal update will take a while but you can follow the progress in the Neo4j browser where you should be able to see drug nodes being loaded.

**Comment by albsantosdel** [comment]
I am closing this issue because because it seems not to be active anymore.
