### ISSUE TITLE
[docker build] Docker image size of 64 Gb instead of 150 Gb

### ISSUE THREAD

**Issue by KR-15** [MannLabs/CKG#70]
Hi,

I was installing the CKG on a windows 10 platform using the tutorial with the following command:

```
$ cd CKG/
$ docker build -t docker-ckg:latest .

```
I think everything went well (see attached log file from windows prompt) but the final image in Docker Desktop is approximately 64 Gb instead of 150 Gb mentioned in the tutorial so I was wondering if this was normal ?

[CKG_container_build_windprompt.txt](https://github.com/MannLabs/CKG/files/7890999/CKG_container_build_windprompt.txt)

Just to notice that following this I have just tried to run the image from Docker Desktop and open it using google chrome web browser and I have succeeded to connect to JupyterHub, Neo4j browser and web browser access CKG app. so I guess connection is ok but what about the size of the image ?

Thank for you feedback.

Best,

KR

**Comment by albsantosdel** [comment]
Hi, 
The final volume of the image is actually lower than 150Gb after some of the changes we made in the dockerfile also depending on whether you include the licensed databases or not. It seems that you successfully built the docker image but to confirm that everything went well, you can check in the Neo4j browser (localhost:7474) the number of nodes and relationships (and types) to make sure that the dump file was correctly loaded into the database. 
If the loading was correct, you should see something like this with maybe different numbers if you included the licensed databases:
![image](https://user-images.githubusercontent.com/1425851/154007711-d360e6af-d1cc-4ccc-9bd0-4201b22cd0c8.png)

I will suggest a change in the documentation to clarify the volume of the image.

**Comment by KR-15** [comment]
Hi @albsantosdel,

Thanks a lot for all of your replies and your valued help. I have seen both of your answers about this issue and issue #71 but as you suggest I will first handle this one.

I took a look on the number of nodes and relationships (and types) of Neo4j browser (localhost:7474) and I think that everything went well. You can see in the screenshots attached my Neo4J browser. Normally, I have also done the minimal update and included the licensed database.

![Neo4J_Node_Labels](https://user-images.githubusercontent.com/72909968/154048453-f79bf22b-c6e5-4cab-942d-8e00e8d1695d.PNG)
![Neo4J_Relationship_types](https://user-images.githubusercontent.com/72909968/154048452-e94e735c-f26b-40d3-94c6-91879ed387c8.PNG)
![Neo4J_Property_keys](https://user-images.githubusercontent.com/72909968/154048448-0cec0497-2082-4396-a154-ce1037f7ba86.PNG)

What do you think ?

Thanks again for your help. I will check now the issue #71 

KR

**Comment by albsantosdel** [comment]
I think it looks good!
