### ISSUE TITLE
Neo4j Enterprise

### ISSUE THREAD

**Issue by rodguinea** [MannLabs/CKG#78]
Thank you for this project. It is really useful. I wanted to ask how could I use the Enterprise version (I already have the appropriate licence, but I have been unable to properly set up the Dockerfile).

**Comment by albsantosdel** [comment]
Hi, 
If you want to use the Enterprise version I believe you will need to specify the right version from https://neo4j.com/download-center/ in the Dockerfile. I am not sure how you can then input the license number but it may be question for Neo4j directly.
