### ISSUE TITLE
Project creation - Project Tissue/Project Disease - No results found

### ISSUE THREAD

**Issue by Mijapi** [MannLabs/CKG#80]
**Describe the bug**
When I try to create a new project and I try to select tissue and disease the drop down list does not contain any entries and I am not able to create projects.
**To Reproduce**
1. Go to Project creation/Project Tissue or Project Disease
2. Click on Drop down arrow
3. No results found

**Expected behavior**
I expect to see different options which I can select from as these two fields are mandatory. However I only get a message No results found.

**Screenshots**
![image](https://user-images.githubusercontent.com/9790496/156903537-6f675afd-3f4c-4e9d-96dc-f26e3c6f210b.png)
![image](https://user-images.githubusercontent.com/9790496/156903550-6d1dde21-412f-44af-bc50-d02dbf31809b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chrome
 - Version: 98.0.4758.102 (Official Build) (64-bit)

**Additional context**
I also see the same problem when I tried to install the Neo4j database and the Python library in Ubuntu. Do I need to build a full CKGs Graph Database with graphdb_builder first before I create a new project?

**Comment by driesheylen123** [comment]
Hi @Mijapi

I have exactly the same problem. Could you find a solution or workaround already? 

@albsantosdel, this currently prevents me from checking whether we will go full-gear on implementing CKG with our research group. Any help would be more than welcome. 

Regards

Dries

**Comment by albsantosdel** [comment]
Hi, 
When following the step by step installation, you need to build the database. This can be done either loading the database dump (https://ckg.readthedocs.io/en/latest/ckg_builder/graphdb-builder.html#building-ckg-s-graph-database-from-a-dump-file) or building it from scratch (downloading and parsing all ontologies and databases) (https://ckg.readthedocs.io/en/latest/ckg_builder/graphdb-builder.html#full-update). 

After building the database, you should be able to see the tissue, disease, etc. options in the form and also have a database filled with nodes and relationships.

**Comment by Mijapi** [comment]
Hi, Thank you for the advice to build the database first. I am able to see the tissue, disease etc. on the project creation site now and have the database filled with nodes and relationships. When I try to create a new project using the browser interface at http://localhost:5000/apps/projectCreationApp
after providing all the information the app goes into an update phase after which it returns to the same screen without creating the project. I do not see any new project identifiers which I could use to upload test datasets or my own data. The Neo4j database and ckg_app run in the background. Am I missing something?

**Comment by Mijapi** [comment]
Hi, I have found out that in order to be able to create a project I had to install WSL (Windows Subsystem for Linux) and Redis server using the following set of instructions: https://redis.io/docs/getting-started/installation/install-redis-on-windows/
Since then I am able to create projects using the web browser interface.
